import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";
import DisableDraftMode from "@/components/DisableDraftMode";


export const metadata: Metadata = {
  title: "Er-Marketplace",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {(await draftMode()).isEnabled && (
        <>
          <DisableDraftMode />
          <VisualEditing />
        </>
      )}
      <Header />
      {children}
      <Footer />
    </div>
  );
}
